# Webbservern brakar me error 403 om int jag definierar att index inte ligger i root foldern..

server{

    listen 8080;

    root /opt/app-root/src/lektion-3-ip-frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

}